/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cily_utils_encrypt_MD5Utils */

#ifndef _Included_com_cily_utils_encrypt_MD5Utils
#define _Included_com_cily_utils_encrypt_MD5Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cily_utils_encrypt_MD5Utils
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cily_utils_encrypt_MD5Utils_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cily_utils_encrypt_MD5Utils
 * Method:    check
 * Signature: (Landroid/content/Context;)Z
 */
JNIEXPORT jint JNICALL Java_com_cily_utils_encrypt_MD5Utils_check
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
